### PR TITLE
feat: images and some link correction

### PR DESCRIPTION
**Pull request by ultronjs**
Addition of Image Component and making sidebar image link active for all pages and correcting link on the landing page and also added gap utility class

### CODE REVIEW

**Comment by JantuDeb** [comment]
> _No description provided._

Add description for pull request.

**Comment by ultronjs** [comment]
@JantuDeb Done

**Review by Raghav888 — APPROVED** [review]
Approved

**Review by atharvabhanage02 — APPROVED** [review]
Clean code and everything looks in place
Can go ahead and merge

**Pull request merged**
