### PR TITLE
feat: added badge component

### PR DESCRIPTION
**Pull request by ultronjs**
Added badge component and some utility class in position and updated sidebar links

### CODE REVIEW

**Review by sks-21 — APPROVED** [review]
The code looks nice, I would suggest you to add some more comments .

**Comment by ultronjs** [comment]
Thanks for the feedback.Will do that

**Comment by kotalwar-krishna** [comment]
Code looks Nice...same aggession write some comments...its make your code understandable to reader easily. Good to merge.

**Comment by atharvabhanage02** [comment]
Good to get merged ! 
Used the classes effectively and avoided repetition

**Pull request merged**
